name: Apple Policy Lint (Swift AST)
description: "AST-based Swift scanner for Apple privacy/compliance signals (fast: downloads prebuilt engine)"
author: skprasadu

inputs:
  root:
    description: "Root directory to scan"
    required: false
    default: "."

  comment:
    description: "Create/update a PR comment"
    required: false
    default: "true"

  fail_on_issues:
    description: "Fail the workflow if issues are found"
    required: false
    default: "true"

  report_md:
    description: "Markdown report output path"
    required: false
    default: "out/apple_policy_report.md"

  report_json:
    description: "JSON report output path"
    required: false
    default: "out/apple_policy_report.json"

  github_annotations:
    description: "Emit GitHub workflow annotations"
    required: false
    default: "true"

  engine_version:
    description: "Engine release tag to download. Use 'auto' to use the action ref (recommended)."
    required: false
    default: "auto"

  p2e_token:
    description: "Optional token for Pro policy packs/features (reserved; engine may ignore today)."
    required: false
    default: ""

  scan:
    description: "Scan mode: full or diff (diff scans only PR-changed Swift files)"
    required: false
    default: "full"

  baseline_json:
    description: "Optional baseline report JSON path. Used with only_new=true."
    required: false
    default: ""

  only_new:
    description: "If true, only report/fail on findings not present in baseline_json."
    required: false
    default: "false"

  config_path:
    description: "Optional config file path (JSON) for ignore rules/paths and future knobs."
    required: false
    default: ""

outputs:
  count:
    description: "Number of issues found"
    value: ${{ steps.lint.outputs.count }}

runs:
  using: "composite"
  steps:
    - name: Compute changed Swift files (scan=diff)
      id: diff
      if: ${{ inputs.scan == 'diff' && (github.event_name == 'pull_request' || github.event_name == 'pull_request_target') }}
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
        REPO: ${{ github.repository }}
        PR_NUMBER: ${{ github.event.pull_request.number }}
      run: |
        set -euo pipefail
        mkdir -p .p2i

        python3 - <<'PY'
        import json, os, urllib.request

        token = os.environ["GH_TOKEN"]
        repo = os.environ["REPO"]
        pr = os.environ["PR_NUMBER"]

        out_path = ".p2i/changed_swift_files.txt"

        files = []
        page = 1
        while True:
            url = f"https://api.github.com/repos/{repo}/pulls/{pr}/files?per_page=100&page={page}"
            req = urllib.request.Request(
                url,
                headers={
                    "Authorization": f"Bearer {token}",
                    "Accept": "application/vnd.github+json",
                    "User-Agent": "apple-policy-lint",
                },
            )
            with urllib.request.urlopen(req) as resp:
                data = json.loads(resp.read().decode("utf-8"))

            if not data:
                break

            for f in data:
                name = f.get("filename", "")
                if name.endswith(".swift"):
                    files.append(name)

            page += 1

        with open(out_path, "w", encoding="utf-8") as fp:
            fp.write("\n".join(files) + ("\n" if files else ""))

        print(f"Wrote {len(files)} Swift files to {out_path}")
        PY

        echo "paths_file=.p2i/changed_swift_files.txt" >> "$GITHUB_OUTPUT"

    - name: Download Apple Policy Lint engine (prebuilt)
      id: engine
      shell: bash
      run: |
        set -euo pipefail

        OS="${{ runner.os }}"
        case "$OS" in
          Linux) OS="linux" ;;
          macOS) OS="macos" ;;
          Windows) OS="windows" ;;
          *) OS="$(echo "$OS" | tr '[:upper:]' '[:lower:]')" ;;
        esac

        ARCH="${{ runner.arch }}"
        case "$ARCH" in
          X64) ARCH="x64" ;;
          ARM64) ARCH="arm64" ;;
          *) ARCH="$(echo "$ARCH" | tr '[:upper:]' '[:lower:]')" ;;
        esac

        PARSED_REPO=""
        PARSED_REF=""

        AP="${GITHUB_ACTION_PATH:-}"
        if [ -n "$AP" ] && [[ "$AP" == *"/_actions/"* ]]; then
          tail="${AP##*/_actions/}"
          owner="${tail%%/*}"
          tail="${tail#*/}"
          repo="${tail%%/*}"
          tail="${tail#*/}"
          ref="${tail%%/*}"

          if [ -n "$owner" ] && [ -n "$repo" ]; then
            PARSED_REPO="$owner/$repo"
          fi
          if [ -n "$ref" ]; then
            PARSED_REF="$ref"
          fi
        fi

        ENGINE_TAG="${{ inputs.engine_version }}"
        if [ "$ENGINE_TAG" = "auto" ]; then
          ENGINE_TAG="${GITHUB_ACTION_REF:-$PARSED_REF}"
        fi

        ENGINE_TAG="${ENGINE_TAG#refs/tags/}"
        ENGINE_TAG="${ENGINE_TAG#refs/heads/}"

        if [ -z "$ENGINE_TAG" ]; then
          echo "ERROR: Could not resolve engine tag."
          echo "Fix: set inputs.engine_version to a release tag like v0.1.7"
          exit 1
        fi

        REPO="${GITHUB_ACTION_REPOSITORY:-$PARSED_REPO}"
        if [ -z "$REPO" ]; then
          REPO="skprasadu/apple-policy-lint"
        fi

        if [ "$OS" != "linux" ] || [ "$ARCH" != "x64" ]; then
          echo "ERROR: This action currently expects a linux-x64 engine asset."
          echo "Runner is: OS=$OS ARCH=$ARCH"
          echo "Fix: run this job on ubuntu-latest, or publish engine assets for this platform."
          exit 1
        fi

        ASSET="apple-policy-lint-${OS}-${ARCH}.tar.gz"
        URL="https://github.com/${REPO}/releases/download/${ENGINE_TAG}/${ASSET}"

        echo "Downloading engine:"
        echo "  repo:  $REPO"
        echo "  tag:   $ENGINE_TAG"
        echo "  asset: $ASSET"

        mkdir -p .p2i/bin
        curl -fsSL -o /tmp/apple-policy-lint.tgz "$URL"
        tar -xzf /tmp/apple-policy-lint.tgz -C .p2i/bin

        ENGINE=".p2i/bin/apple-policy-lint"
        if [ ! -x "$ENGINE" ]; then
          echo "ERROR: Engine executable not found or not executable: $ENGINE"
          echo "The release asset must contain an executable named: apple-policy-lint"
          echo "Extracted files:"
          ls -la .p2i/bin || true
          exit 1
        fi

        chmod +x "$ENGINE" || true
        echo "engine_path=$ENGINE" >> "$GITHUB_OUTPUT"

    - name: Run policy lint
      id: lint
      shell: bash
      run: |
        set -euo pipefail

        if [ -n "${{ inputs.p2e_token }}" ]; then
          export P2E_TOKEN="${{ inputs.p2e_token }}"
        fi

        ENGINE="${{ steps.engine.outputs.engine_path }}"
        echo "Using engine: $ENGINE"

        EXTRA_ARGS=""

        if [ "${{ inputs.scan }}" = "diff" ] && { [ "${{ github.event_name }}" = "pull_request" ] || [ "${{ github.event_name }}" = "pull_request_target" ]; }; then
          PF="${{ steps.diff.outputs.paths_file }}"
          if [ -n "$PF" ] && [ -f "$PF" ]; then
            EXTRA_ARGS="$EXTRA_ARGS --paths-file $PF"
          fi
        fi

        if [ -n "${{ inputs.baseline_json }}" ]; then
          EXTRA_ARGS="$EXTRA_ARGS --baseline-json ${{ inputs.baseline_json }}"
        fi

        if [ "${{ inputs.only_new }}" = "true" ]; then
          EXTRA_ARGS="$EXTRA_ARGS --only-new"
        fi

        if [ -n "${{ inputs.config_path }}" ]; then
          EXTRA_ARGS="$EXTRA_ARGS --config ${{ inputs.config_path }}"
        fi

        "$ENGINE" lint \
          --root "${{ inputs.root }}" \
          --report "${{ inputs.report_md }}" \
          --json "${{ inputs.report_json }}" \
          $([ "${{ inputs.github_annotations }}" = "true" ] && echo "--github-annotations" || true) \
          $EXTRA_ARGS

        COUNT=$(python3 -c 'import json,sys; print(json.load(open(sys.argv[1]))["count"])' "${{ inputs.report_json }}")
        echo "count=$COUNT" >> "$GITHUB_OUTPUT"

    - name: Find existing bot comment
      if: ${{ inputs.comment == 'true' && (github.event_name == 'pull_request' || github.event_name == 'pull_request_target') }}
      uses: peter-evans/find-comment@v4
      id: fc
      with:
        issue-number: ${{ github.event.pull_request.number }}
        body-includes: "<!-- apple-policy-bot -->"

    - name: Create or update PR comment
      if: ${{ inputs.comment == 'true' && (github.event_name == 'pull_request' || github.event_name == 'pull_request_target') }}
      uses: peter-evans/create-or-update-comment@v4
      with:
        token: ${{ github.token }}
        comment-id: ${{ steps.fc.outputs.comment-id }}
        issue-number: ${{ github.event.pull_request.number }}
        body-path: ${{ inputs.report_md }}

    - name: Fail if issues found
      if: ${{ inputs.fail_on_issues == 'true' && steps.lint.outputs.count != '0' }}
      shell: bash
      run: exit 1