name: Apple Policy Lint (Swift AST)
description: "AST-based Swift scanner for Apple privacy/compliance signals (PoC rulepack hardcoded)"
author: skprasadu

inputs:
  root:
    description: "Root directory to scan"
    required: false
    default: "."
  comment:
    description: "Create/update a PR comment"
    required: false
    default: "true"
  fail_on_issues:
    description: "Fail the workflow if issues are found"
    required: false
    default: "true"
  report_md:
    description: "Markdown report output path"
    required: false
    default: "out/swift_policy_report.md"
  report_json:
    description: "JSON report output path"
    required: false
    default: "out/swift_policy_report.json"
  github_annotations:
    description: "Emit GitHub workflow annotations"
    required: false
    default: "true"

outputs:
  count:
    description: "Number of issues found"
    value: ${{ steps.lint.outputs.count }}

runs:
  using: "composite"
  steps:
    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Setup Python (only to parse JSON for output)
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Run policy lint
      id: lint
      shell: bash
      run: |
        set -euo pipefail

        # Run the Rust linter (builds on first run)
        cargo run --release --manifest-path "${{ github.action_path }}/Cargo.toml" -- lint \
          --root "${{ inputs.root }}" \
          --report "${{ inputs.report_md }}" \
          --json "${{ inputs.report_json }}" \
          $([ "${{ inputs.github_annotations }}" = "true" ] && echo "--github-annotations" || true)

        COUNT=$(python3 -c 'import json,sys; print(json.load(open(sys.argv[1]))["count"])' "${{ inputs.report_json }}")
        echo "count=$COUNT" >> "$GITHUB_OUTPUT"

    - name: Find existing bot comment
      if: ${{ inputs.comment == 'true' && (github.event_name == 'pull_request' || github.event_name == 'pull_request_target') }}
      uses: peter-evans/find-comment@v4
      id: fc
      with:
        issue-number: ${{ github.event.pull_request.number }}
        body-includes: "<!-- swift-policy-bot -->"

    - name: Create or update PR comment
      if: ${{ inputs.comment == 'true' && (github.event_name == 'pull_request' || github.event_name == 'pull_request_target') }}
      uses: peter-evans/create-or-update-comment@v4
      with:
        comment-id: ${{ steps.fc.outputs.comment-id }}
        issue-number: ${{ github.event.pull_request.number }}
        body-path: ${{ inputs.report_md }}

    - name: Fail if issues found
      if: ${{ inputs.fail_on_issues == 'true' && steps.lint.outputs.count != '0' }}
      shell: bash
      run: exit 1